export const ACTIONS = {
  GET_ALL_ROOMS: 'GET_ALL_ROOMS',
  GET_ONE_ROOM: 'GET_ONE_ROOM',
  GET_CURRENT_HOUSE: 'GET_CURRENT_HOUSE',
  OPEN_EDIT_MODAL: 'OPEN_EDIT_MODAL',
  GET_EDITED_ROOM: 'GET_EDITED_ROOM',

  GET_ALL_DEVICES: 'GET_ALL_DEVICES',
  GET_ONE_DEVICE: 'GET_ONE_DEVICE',
  OPEN_DEVICE_MODAL: 'OPEN_DEVICE_MODAL',
  GET_DB: 'GET_DB',
};
